common/models/Projects.php
<?php

namespace common\models;

use Yii;
use yii\db\ActiveRecord;
use yii\web\UploadedFile;
use common\helpers\MainHelper;

/**
 * This is the model class for table "projects".
 *
 * @property int $id
 * @property string $name
 * @property string $photo
 * @property string $description
 * @property string $vendor_code
 * @property string $price
 * @property int $user_id
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 */
class Projects extends ActiveRecord
{
    const ACTIVE = 1;
    const IN_CONSIDERED = 2;
    const INACTIVE = 3;
    const DELETED = 0;

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            [
                'class' => 'yii\behaviors\TimestampBehavior',
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
            ]
        ];
    }

    public static function getStatuses(){
        return [
            self::ACTIVE => 'Active',
            self::IN_CONSIDERED => 'In considered',
            self::INACTIVE => 'Inactive',
            self::DELETED => 'Deleted'
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'projects';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            ['photo', 'image', 'skipOnEmpty' => true, 'extensions' => 'png, jpg', 'minWidth' => 100, 'maxWidth' => 1000, 'minHeight' => 100, 'maxHeight' => 1000,],
            [['name', 'user_id', 'status'], 'required'],
            [['created_at', 'updated_at'], 'safe'],
            [['user_id', 'price', 'status', 'created_at', 'updated_at'], 'integer'],
            [['name', 'vendor_code'], 'string', 'max' => 255],
            [['description'], 'string', 'max' => 1000],
            [['name'], 'unique']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app','ID'),
            'name' => Yii::t('app','Name'),
            'photo' => Yii::t('app','Photo'),
            'description' => Yii::t('app','Description'),
            'vendor_code' => Yii::t('app','Vendor Code'),
            'price' => Yii::t('app','Price'),
            'user_id' => Yii::t('app','User ID'),
            'status' => Yii::t('app','Status'),
            'created_at' => Yii::t('app','Created At'),
            'updated_at' => Yii::t('app','Updated At'),
        ];
    }

    public function afterDelete()
    {
        parent::afterDelete();

    }

    public function uploadFiles(UploadedFile $fileInstanse){
        $file = MainHelper::setUniqueFileName($fileInstanse->baseName, $fileInstanse->extension);
        $path = $this->getUploadsPath();
        if(!is_dir($path)){
            mkdir($path, 0777, true);
        }
        if($fileInstanse->saveAs($path.$file)){
            return $file;
        }
        return false;
    }

    public function deleteFiles($name=false){
        $path = $this->getUploadsPath();
        if(is_dir($path)){
            if(file_exists($path.$name)){
                unlink($path.$name);
                MainHelper::remove_if_dir_empty($path);
            }
            else{
                MainHelper::remove_dir($path);
            }
        }
    }

    public function getUploadsUrl(){
        return Yii::$app->params['frontendHost'].'uploads/projects/'.$this->id.'/';
    }

    public function getUploadsPath(){
        return Yii::getAlias('@uploads').'\projects\\'.$this->id.'\\';
    }

    public function getUser(){
        return $this->hasOne(Profile::class, ['id' => 'user_id']);
    }

}

backend/controllers/ProjectsController.php
<?php

namespace backend\controllers;

use common\models\LoginForm;
use Yii;
use common\models\Projects;
use common\models\ProjectsSearch;
use yii\helpers\BaseVarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\ProfileSearch;
use yii\web\UploadedFile;
use common\models\Links;
use common\models\LinksForm;
use common\components\parser\Parser;

use core\forms\ProjectsForm;
use core\services\ProjectService;
use core\entity\Project;
use yii\base\Module;

/**
 * ProjectsController implements the CRUD actions for Projects model.
 */
class ProjectsController extends Controller
{
    private $service;

    public function __construct($id, Module $module, array $config = [], ProjectService $service)
    {
        parent::__construct($id, $module, $config);
        $this->service = $service;
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ]
        ];
    }

    /**
     * Lists all Projects models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProjectsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionGetIframe($url=false, $layout=false){
        if($url){
            $url = base64_decode($url);
            $this->layout = $layout;
            return $this->renderPartial('iframe', [
                'url' => $url,
                'layout' => $layout
            ]);
        }
        return false;
    }

    public function actionGetUsers($layout=false)
    {
        $searchModel = new ProfileSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $dataProvider->pagination = ['pageSize' => 5];
        $dataProvider->sort = ['defaultOrder' => ['created_at' => SORT_DESC]];

        if($layout){
            $this->layout = $layout;
        }
        return $this->render('view-users', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Projects model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Projects model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate(){
        $projectsForm = new ProjectsForm();
        if($projectsForm->load(Yii::$app->request->post())){
            $projectsForm->photo = $projectsForm->photo?$projectsForm->photo:UploadedFile::getInstance($projectsForm, 'photo');
            if($projectsForm->validate()){
                $project = $this->service->create($projectsForm);
                return $this->redirect(['view', 'id' => $project->id]);
            }
        }
        return $this->render('_create', [
            'projectsForm' => $projectsForm,
        ]);
    }

    public function actionUpdate($id){
        $project = $this->findModel($id);
        $projectsForm = new ProjectsForm($project);
        if($projectsForm->load(Yii::$app->request->post())){
            $projectsForm->photo = $projectsForm->photo?$projectsForm->photo:UploadedFile::getInstance($projectsForm, 'photo');
            if($projectsForm->validate()){
                $this->service->edit($projectsForm, $project->id);
                return $this->redirect(['view', 'id' => $project->id]);
            }
        }
        return $this->render('_update', [
            'project' => $project,
            'projectsForm' => $projectsForm
        ]);
    }

    /**
     * Deletes an existing Projects model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the Projects model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Project the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Project::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/ProjectsController.php
<?php

namespace frontend\controllers;

use core\entity\Project;
use core\forms\ProjectsForm;
use core\services\ProjectService;
use Yii;
use yii\base\Module;
use yii\data\ActiveDataProvider;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;

/**
 * ProjectsController implements the CRUD actions for Project model.
 */
class ProjectsController extends Controller
{

    private $service;

    public function __construct($id, Module $module, array $config = [], ProjectService $service)
    {
        parent::__construct($id, $module, $config);
        $this->service = $service;
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Project models.
     * @return mixed
     */
    public function actionIndex()
    {
        $query = Project::find()->where('status >= 1 and user_id = '.Yii::$app->user->id);
        $countQuery = clone $query;
        $pages = new Pagination([
            'pageSize'=>20,
            'totalCount' => $countQuery->count(),
        ]);
        $dataProvider = new ActiveDataProvider([
            'query' => $query->offset($pages->offset)->limit($pages->limit),
            'pagination' => false,
            'sort' => [
                'defaultOrder' => [
                    'created_at' => SORT_DESC,
                ]
            ],
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'pages' => $pages,
        ]);
    }

    /**
     * Creates a new Project model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $projectsForm = new ProjectsForm();
        if($projectsForm->load(Yii::$app->request->post())){
            $projectsForm->photo = UploadedFile::getInstance($projectsForm, 'photo');
            $projectsForm->user_id = Yii::$app->user->id;
            if($projectsForm->validate()){
                $this->service->create($projectsForm);
                return $this->redirect(['index']);
            }
        }
        return $this->render('create', [
            'model' => $projectsForm,
        ]);
    }

    /**
     * Updates an existing Project model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $project = $this->findModel($id);
        if(!$this->isOwner($project->user_id)){
            return $this->redirect(['index']);
        }
        $projectsForm = new ProjectsForm($project);
        if($projectsForm->load(Yii::$app->request->post())) {
            $projectsForm->photo = UploadedFile::getInstance($projectsForm, 'photo');
            $projectsForm->user_id = Yii::$app->user->id;
            $projectsForm->id = $project->id;
            if ($projectsForm->validate()){
                $this->service->edit($projectsForm, $project->id);
                return $this->redirect(['index']);
            }
        }

        return $this->render('update', [
            'model' => $projectsForm,
            'project' => $project
        ]);
    }

    public function isOwner($id){
        return $id == Yii::$app->user->id;
    }

    public function actionRemoveImage($id){
        if(Yii::$app->request->isAjax){
            $project = $this->findModel($id);
            if($this->isOwner($project->user_id)){
                $project->photo = null;
                $project->deleteFiles($project->oldAttributes['photo']);
                return $project->save();
            }
        }
        return false;
    }

    /**
     * Deletes an existing Project model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $project = $this->findModel($id);
        if($this->isOwner($project->user_id)){
            $project->delete();
        }

        return $this->redirect(['index']);
    }

    /**
     * Finds the Project model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Project the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Project::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

backend/views/projects/_create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use common\models\Projects;


/* @var $this yii\web\View */
/* @var $model core\forms\ProjectsForm */

$this->title = 'Create Projects';
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="projects-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($projectsForm, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($projectsForm, 'description')->textarea(['maxlength' => true]) ?>

    <?= $form->field($projectsForm, 'photo')->fileInput(['class'=>'hiddenEl fileInputField']) ?>

    <div class="file-input-content">
        <?= Html::button(Yii::t('app', 'Add photo'), ['data-filename'=>'ProjectsForm[photo]', 'class' => 'fileNameButton btn btn-success']) ?>
        <div class="image-container"></div>
    </div>

    <?= $form->field($projectsForm, 'vendor_code')->textInput(['maxlength' => true]) ?>

    <?= $form->field($projectsForm, 'price')->textInput(['maxlength' => true, 'type'=>'number']) ?>

    <?= $form->field($projectsForm, 'user_id')->hiddenInput() ?>

    <div class="form-group">
        <?= Html::button(Yii::t('app', 'Add user'), [
            'data-name'=>'ProjectsForm[user_id]',
            'id'=>'getUsers',
            'class'=>'btn btn-success',
            'data-url'=>Url::to(['projects/get-iframe',
                'url'=>base64_encode('/projects/get-users'), 'layout'=>'mainBlank'])]) ?>
        <div class="userResult"></div>
    </div>

    <?= $form->field($projectsForm, 'status')->dropDownList(Projects::getStatuses()) ?>


    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

    <?php yii\bootstrap\Modal::begin([
        'id'=>'pModal',
        'header'=>'<h4>'.Yii::t('app', 'Add user').'</h4>',
        'size'=>'modal-lg',
    ]); ?>
    <div class="pModal-content"></div>
    <?php yii\bootstrap\Modal::end(); ?>

</div>

backend/views/projects/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\Projects;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\Projects */
/* @var $form yii\widgets\ActiveForm */

/*высчитывать разницу между двумя timestamp
$today = strtotime('2018-08-27 00:00:00');
$yesterday = strtotime('2018-08-26 02:59:59');
print_r(date('Y-m-d H:i:s', $today));
echo '<br>';
print_r(date('Y-m-d H:i:s', $yesterday));
echo '<br>';
var_dump(round(($today-$yesterday)/3600, 2));//in hours
die;
*/
?>

<div class="projects-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textarea(['maxlength' => true]) ?>

    <?= $form->field($model, 'photo')->fileInput(['class'=>'hiddenEl fileInputField']) ?>

    <div class="file-input-content">
        <?= Html::button(Yii::t('app', 'Add photo'), ['data-filename'=>'Projects[photo]', 'class' => 'fileNameButton btn btn-success']) ?>
        <div class="image-container">
            <?php
            if($model->photo){
                echo '<img src="'.$model->getUploadsUrl().$model->photo.'"><div data-filename="Projects[photo]" class="close-img-button"><span class="fa fa-times-circle"></span></div>';
            }
            ?>
        </div>
    </div>

    <?= $form->field($model, 'vendor_code')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'user_id')->hiddenInput() ?>

    <div class="form-group">
        <?= Html::button(Yii::t('app', 'Add user'), [
            'data-name'=>'user_id',
            'id'=>'getUsers',
            'class'=>'btn btn-success',
            'data-url'=>Url::to(['projects/get-iframe',
            'url'=>base64_encode('/projects/get-users'), 'layout'=>'mainBlank'])]) ?>
        <div class="userResult">
            <?php if($model->user): ?>
            ID: <span><?= $model->user->attributes['id'] ?></span><span><?= $model->user->attributes['username'] ?></span><span><?= $model->user->attributes['email'] ?></span><span><?= date('Y-m-d H:i:s', $model->user->attributes['created_at']) ?></span><span><?= date('Y-m-d H:i:s', $model->user->attributes['updated_at']) ?></span>
            <?php endif; ?>
        </div>
    </div>

    <?= $form->field($model, 'status')->dropDownList(Projects::getStatuses()) ?>

    <div class="form-group">
        <label class="control-label"><?= Yii::t('app', 'Urls') ?></label>
        <div class="fields-container">
            <div class="form-group">
                <?= Html::textInput('DynamicFields_url[]', '', ['class' => 'dynamicField form-control']) ?>
                <span class="fieldRemoveButton fa fa-close"></span>
            </div>
        </div>
        <?= Html::button(Yii::t('app', 'Add url'), ['class' => 'addField btn btn-success']) ?>
    </div>


    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

    <?php yii\bootstrap\Modal::begin([
            'id'=>'pModal',
            'header'=>'<h4>'.Yii::t('app', 'Add user').'</h4>',
            'size'=>'modal-lg',
    ]); ?>
    <div class="pModal-content"></div>
    <?php yii\bootstrap\Modal::end(); ?>

</div>

backend/views/projects/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\ProjectsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="projects-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'photo') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'vendor_code') ?>

    <?php // echo $form->field($model, 'user_id') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/projects/_update.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use common\models\Projects;

/* @var $this yii\web\View */
/* @var $projectsForm core\forms\ProjectsForm */
/* @var $project core\entity\Project */

$this->title = 'Create Projects';
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="projects-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($projectsForm, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($projectsForm, 'description')->textarea(['maxlength' => true]) ?>

    <?= $form->field($projectsForm, 'photo')->fileInput(['class'=>'hiddenEl fileInputField']) ?>

    <div class="file-input-content">
        <?= Html::button(Yii::t('app', 'Add photo'), ['data-filename'=>'ProjectsForm[photo]', 'class' => 'fileNameButton btn btn-success']) ?>
        <div class="image-container">
            <?php
            if($projectsForm->photo){
                echo '<img src="'.$project->getUploadsUrl($project->id, $projectsForm->photo).'"><div data-filename="ProjectsForm[photo]" class="close-img-button"><span class="fa fa-times-circle"></span></div>';
            }
            ?>
        </div>
    </div>

    <?= $form->field($projectsForm, 'vendor_code')->textInput(['maxlength' => true]) ?>

    <?= $form->field($projectsForm, 'price')->textInput(['maxlength' => true, 'type'=>'number']) ?>

    <?= $form->field($projectsForm, 'user_id')->hiddenInput() ?>

    <div class="form-group">
        <?= Html::button(Yii::t('app', 'Add user'), [
            'data-name'=>'ProjectsForm[user_id]',
            'id'=>'getUsers',
            'class'=>'btn btn-success',
            'data-url'=>Url::to(['projects/get-iframe',
                'url'=>base64_encode('/projects/get-users'), 'layout'=>'mainBlank'])]) ?>
        <div class="userResult">
            <?php if($project->user): ?>
                ID: <span><?= $project->user->attributes['id'] ?></span><span><?= $project->user->attributes['username'] ?></span><span><?= $project->user->attributes['email'] ?></span><span><?= date('Y-m-d H:i:s', $project->user->attributes['created_at']) ?></span><span><?= date('Y-m-d H:i:s', $project->user->attributes['updated_at']) ?></span>
            <?php endif; ?>
        </div>
    </div>

    <?= $form->field($projectsForm, 'status')->dropDownList(Projects::getStatuses()) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

    <?php yii\bootstrap\Modal::begin([
        'id'=>'pModal',
        'header'=>'<h4>'.Yii::t('app', 'Add user').'</h4>',
        'size'=>'modal-lg',
    ]); ?>
    <div class="pModal-content"></div>
    <?php yii\bootstrap\Modal::end(); ?>

</div>

backend/views/projects/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\Projects */

$this->title = 'Create Projects';
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="projects-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/projects/iframe.php
<iframe id="ajaxIframe" src="<?php echo $url.'?layout='.$layout; ?>"></iframe>

backend/views/projects/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\ProjectsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Projects';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="projects-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Projects', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',
            'description',
            'vendor_code',
            [
                'label' => Yii::t('app', 'Photo'),
                'format' => 'html',
                'value' => function($model) {
                    return $model->photo? Html::img($model->getUploadsUrl($model->id, $model->photo), ['style' => 'max-width: 150px;']) : Yii::t('app', 'No photo');
                }
            ],
            [
                'label' => Yii::t('app','Links'),
                'attribute' => 'links',
                'format' => 'raw',
                'value'=>function ($data) {
                    return count($data->links);
                },
            ],
            'user_id',
            [
                'attribute' => 'status',
                'label' => Yii::t('app','Status'),
                'format' => 'raw',
                'filter' => $searchModel->getStatuses(),
                'value'=>function ($data) {
                    $statusArr = $data->getStatuses();
                    if(isset($statusArr[$data->status])){
                        return Html::a($statusArr[$data->status], ['/projects/change-status', 'id'=>$data->id]);
                    }
                    return Yii::t('app','Status not set');
                },
            ],
            [
                'attribute' => 'created_at',
                'label' => Yii::t('app','Created'),
                'value'=>function ($data) {
                    return $date = date('Y-m-d H:i:s', $data->created_at);
                },
            ],
            [
                'attribute' => 'updated_at',
                'label' => Yii::t('app','Updated'),
                'value'=>function ($data) {
                    return $date = date('Y-m-d H:i:s', $data->updated_at);
                },
            ],

            ['class' => 'yii\grid\ActionColumn',
                'template' =>'{view} {update} {delete} {links}',
                'buttons' => [
                    'links' => function ($url, $model, $key) {
                        return Html::a('<span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> ', ['projects-links/index', 'project_id' => $model->id], ['title' => Yii::t('app','Links')]);
                    },
                ],
            ],
        ],
    ]); ?>
</div>

backend/views/projects/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Projects */

$this->title = 'Update Projects: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="projects-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/projects/view-users.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\ProjectsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
?>
<div class="users-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            ['class' => 'yii\grid\RadioButtonColumn'],
            'id',
            [
                'attribute' => 'username',
                'label' => Yii::t('app','User name'),
                'value'=>function ($data) {
                    return $data->username;
                },
            ],
            'email',
            [
                'attribute' => 'created_at',
                'label' => Yii::t('app','Created'),
                'value'=>function ($data) {
                    return $date = date('Y-m-d H:i:s', $data->created_at);
                },
            ],
            [
                'attribute' => 'updated_at',
                'label' => Yii::t('app','Updated'),
                'value'=>function ($data) {
                    return $date = date('Y-m-d H:i:s', $data->updated_at);
                },
            ]
        ],
    ]); ?>

    <div class="form-group">
        <?= Html::button('Select', ['class' => 'btn btn-success', 'id'=>'selectItem']) ?>
    </div>

</div>