common/models/ProjectsLinks.php
<?php

namespace common\models;

use core\entity\Project;
use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "projects_links".
 *
 * @property int $id
 * @property int $link_id
 * @property int $project_id
 * @property string $options
 * @property int $link_status
 * @property int $created_at
 * @property int $updated_at
 */
class ProjectsLinks extends ActiveRecord
{
    const ACTIVE = 1;
    const INACTIVE = 2;
    const DELETED = 0;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'projects_links';
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            [
                'class' => 'yii\behaviors\TimestampBehavior',
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
            ]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['link_id', 'project_id', 'link_status'], 'required'],
            [['link_id', 'project_id', 'link_status', 'created_at', 'updated_at'], 'integer'],
            [['options'], 'string', 'max' => 1000],
            ['link_id', 'unique', 'filter' => $this->link_id&&$this->project_id?['and', ['<>', 'link_id', $this->link_id], ['<>', 'project_id', $this->project_id]]:null]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'link_id' => Yii::t('app', 'Link ID'),
            'project_id' => Yii::t('app', 'Project ID'),
            'options' => Yii::t('app', 'Options'),
            'link_status' => Yii::t('app', 'Link Status'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    public static function getStatuses($status=null){
        $statuses = [
            self::ACTIVE=>Yii::t('app', 'Active'),
            self::INACTIVE=>Yii::t('app', 'Inactive')
        ];
        if(isset($statuses[$status])){
            return $statuses[$status];
        }
        return $statuses;
    }

    public function getLink(){
        return $this->hasOne(Links::class, ['id' => 'link_id']);
    }

    public function getHistory(){
        return $this->hasMany(LinksHistory::class, ['link_id' => 'link_id']);
    }

    public function getProject(){
        return $this->hasOne(Project::class, ['id' => 'project_id']);
    }

}

backend/controllers/ProjectsLinksController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\ProjectsLinks;
use common\models\ProjectsLinksSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\LinksForm;
use common\models\Links;
use common\components\parser\classes\BaseParser;
use yii\base\Model;
use yii\filters\AccessControl;

/**
 * ProjectsLinksController implements the CRUD actions for ProjectsLinks model.
 */
class ProjectsLinksController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ]
                ]
            ]
        ];
    }

    /**
     * Lists all ProjectsLinks models.
     * @param mixed $project_id
     * @return mixed
     */
    public function actionIndex($project_id=null)
    {
        if(!$project_id){
            $this->redirect(['/projects/index']);
        }
        $searchModel = new ProjectsLinksSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $project_id);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'project_id' => $project_id
        ]);
    }

    /**
     * Displays a single ProjectsLinks model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ProjectsLinks model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @param mixed $project_id
     * @return mixed
     */
    public function actionCreate($project_id=null){
        if(!$project_id){
            $this->redirect(['/projects-links/index']);
        }
        $links = [new LinksForm()];
        $count = count(Yii::$app->request->post('LinksForm', []));
        for ($i = 1; $i < $count; $i++) {
            $links[] = new LinksForm();
        }
        if(Model::loadMultiple($links, Yii::$app->request->post()) && Model::validateMultiple($links)){
            $domains = BaseParser::getDomains();
            $urls = array_column($links, 'url');
            $LinksModels = array_column(Links::find()->where(['in', 'link_url', $urls])->all(), null, 'id');
            $existingLinks = array_column($LinksModels,'link_url', 'id');
            $errors = [
                'domains'=>[],
                'links'=>[],
                'projectLinks'=>[]
            ];
            foreach ($links as $model){
                $url = parse_url($model->url);
                $domain = @$url['host'];
                if(!in_array($domain, $domains)){
                    //отправить запрос если нет домена в списке
                    $errors['domains'][] = Yii::t('app', "$domain is not supported!");
                }
                else{
                    if($id = array_search($model->url, $existingLinks)){
                        $ProjectsLinks = new ProjectsLinks();
                        $ProjectsLinks->link_id = $id;
                        $ProjectsLinks->project_id = $project_id;
                        $ProjectsLinks->link_status = $model->status;
                        if(!$ProjectsLinks->save()){
                            $errors['projectLinks'][] = Yii::t('app', "$model->url was not added to project!").' ('.$ProjectsLinks->errors['link_id'][0].')';
                        }
                    }
                    else{
                        $Links = new Links();
                        $Links->link_url = $model->url;
                        $Links->status = 1;
                        if($Links->save()){
                            $ProjectsLinks = new ProjectsLinks();
                            $ProjectsLinks->link_id = $Links->id;
                            $ProjectsLinks->project_id = $project_id;
                            $ProjectsLinks->link_status = $model->status;
                            if(!$ProjectsLinks->save()){
                                $errors['projectLinks'][] = Yii::t('app', "$model->url was not added to project!").' ('.$ProjectsLinks->errors['link_id'][0].')';
                            }
                        }
                        else{
                            $errors['links'][] = Yii::t('app', "$model->url was not created!");
                        }
                    }
                }
            }
            if(!empty($errors['domains']) || !empty($errors['links']) || !empty($errors['projectLinks'])){
                $message = implode(' <br>', $errors['domains']).implode(' <br>', $errors['links']).implode(' <br>', $errors['projectLinks']);
                \Yii::$app->getSession()->setFlash('error',  $message);
                if(count($urls)>count($errors['domains'])&&count($urls)>count($errors['links'])&&count($urls)>count($errors['projectLinks'])){
                    \Yii::$app->getSession()->setFlash('success',  Yii::t('app', 'All rest valid links was added!'));
                }
            }
            else{
                \Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Links was successfully saved!'));
            }
            return $this->redirect(['projects-links/index', 'project_id' => $project_id]);
        }

        return $this->render('create', [
            'links' => $links,
            'project_id' => $project_id
        ]);
    }

    /**
     * Updates an existing ProjectsLinks model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $linksForm = new LinksForm($model);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
            'linksForm' => $linksForm
        ]);
    }

    /**
     * Deletes an existing ProjectsLinks model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id, $project_id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionChangeStatus(){
        $request = Yii::$app->request->post();
        if(Yii::$app->request->isAjax && @$request['status']>=0 && @$request['id']>0 && @$request['project_id']>0){
            $projectLink = ProjectsLinks::findOne(['id'=>$request['id'], 'project_id'=>$request['project_id']]);
            if($projectLink && !empty($statuses = $projectLink->getStatuses()) && isset($statuses[$request['status']])){
                $projectLink->link_status = $request['status'];
                if($projectLink->save()){
                    Yii::$app->session->setFlash('success', Yii::t('app', 'Status was changed!'));
                    return $this->redirect(Yii::$app->getRequest()->getReferrer());
                }
                else{
                    Yii::$app->session->setFlash('error', Yii::t('app', 'Status was not changed!'));
                    return $this->redirect(Yii::$app->getRequest()->getReferrer());
                }
            }
        }
        throw new NotFoundHttpException();
    }

    /**
     * Finds the ProjectsLinks model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ProjectsLinks the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ProjectsLinks::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

backend/views/projects-links/create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\ProjectsLinks;

/* @var $this yii\web\View */
/* @var $model common\models\ProjectsLinks */
/* @var $form yii\widgets\ActiveForm */

$class = 'LinksForm';

$this->title = Yii::t('app', 'Create Projects Links');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Projects Links'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="projects-links-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="projects-links-form">

        <?php $form = ActiveForm::begin(); ?>

        <div class="form-group">
            <div class="fields-container">

                <?php foreach ($links as $index => $link): ?>
                    <div data-class="<?= $class; ?>" class="dynamic-form-group">
                        <?= $form->field($link, "[$index]url")->textInput(['data-name'=>'url', 'class'=>'dynamicField form-control', 'id'=>$class."[$index][url]"]) ?>
                        <?= $form->field($link, "[$index]status")->dropDownList(ProjectsLinks::getStatuses(),['data-name'=>'status', 'class'=>'dynamicField form-control', 'id'=>$class."[$index][status]"])->label('') ?>
                        <?= $form->field($link, "[$index]project_id")->hiddenInput(['data-name'=>'project_id', 'class'=>'dynamicField form-control', 'value'=>$project_id, 'id'=>$class."[$index][project_id]"])->label('') ?>
                        <span class="fieldRemoveButton fa fa-close"></span>
                    </div>
                <?php endforeach; ?>

            </div>
            <?= Html::button(Yii::t('app', 'Add url'), ['class' => 'addField btn btn-success']) ?>
        </div>

        <div class="form-group">
            <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    </div>

</div>

backend/views/projects-links/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use kartik\daterange\DateRangePicker;
use common\models\Links;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\ProjectsLinksSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Projects Links').' of '.Yii::t('app', 'Project').': '.$project_id;
$this->params['breadcrumbs'][] = $this->title;

$linksStatuses = Links::getStatuses();
?>
<div class="projects-links-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create Projects Links'), ['create', 'project_id'=>$project_id], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            [
                'label' => Yii::t('app','Links'),
                'attribute' => 'link',
                'value' => 'link.link_url'
            ],
            'link_id',
            [
                'label' => Yii::t('app', "Created"),
                'attribute' => 'created_at',
                'format' => ['date', 'php:Y-m-d H:i:s'],
                'filter' => DateRangePicker::widget([
                    'model'=>$searchModel,
                    'language' => Yii::$app->language,
                    'attribute'=>'createTimeRange',
                    'convertFormat'=>true,
                    'pluginOptions'=>[
                        'timePicker'=>true,
                        'timePicker24Hour' => true,
                        'timePickerIncrement'=>1,
                        'locale'=>[
                            'format'=>'Y-m-d H:i:s'
                        ]
                    ]
                ])
            ],
            [
                'label' => Yii::t('app', "Updated"),
                'attribute' => 'updated_at',
                'format' => ['date', 'php:Y-m-d H:i:s'],
                'filter' => DateRangePicker::widget([
                    'model'=>$searchModel,
                    'language' => Yii::$app->language,
                    'attribute'=>'updateTimeRange',
                    'convertFormat'=>true,
                    'value' => date('Y-m-d H:i:s', strtotime('now -1 month')).' - '. date('Y-m-d H:i:s', strtotime('now +1 month')),
                    'pluginOptions'=>[
                        'timePicker'=>true,
                        'timePicker24Hour' => true,
                        'timePickerIncrement'=>1,
                        'locale'=>[
                            'format'=>'Y-m-d H:i:s'
                        ]
                    ]
                ])
            ],
            [
                'attribute' => 'link_status',
                'label' => Yii::t('app','Link status'),
                'format' => 'raw',
                'filter' => $searchModel->getStatuses(),
                'value'=> function ($data) use ($project_id) {
                    $statusArr = $data->getStatuses();
                    return Html::dropDownList(
                        'link_status',
                        isset($statusArr[$data->link_status])?$data->link_status:null,
                        $statusArr,
                        [
                            'data-csrf'=>Yii::$app->getRequest()->getCsrfToken(),
                            'data-id'=>$data->id,
                            'data-project_id'=>$project_id,
                            'class'=>'form-control changeStatus'
                        ]);
                },
            ],
            [
                'attribute' => 'availability',
                'label' => Yii::t('app','Availability'),
                'format' => 'raw',
                'filter' => $linksStatuses ,
                'value'=> function ($data) use ($linksStatuses){
                    return isset($linksStatuses[$data->link->status])?$linksStatuses[$data->link->status]:null;
                },
            ],

            ['class' => 'yii\grid\ActionColumn',
                'template' =>'{delete}',
                'buttons' => [
                    'delete' => function ($url, $model, $key)use($project_id) {
                        return Html::a('<span class="glyphicon glyphicon-trash" aria-hidden="true"></span> ', ['projects-links/delete', 'id'=>$model->id, 'project_id'=>$project_id], ['title'=>Yii::t('app','Delete'), 'data-method'=>"post"]);
                    },
                ],
            ],
        ],
    ]); ?>
</div>

backend/views/projects-links/update.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\ProjectsLinks;

/* @var $this yii\web\View */
/* @var $model common\models\ProjectsLinks */

$this->title = Yii::t('app', 'Update Projects Links: ' . $model->id, [
    'nameAttribute' => '' . $model->id,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Projects Links'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="projects-links-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="projects-links-form">

        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($linksForm, "url")->textInput() ?>
        <?= $form->field($linksForm, "status")->dropDownList(ProjectsLinks::getStatuses()) ?>

        <div class="form-group">
            <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    </div>

</div>

backend/views/projects-links/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\ProjectsLinks */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Projects Links'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="projects-links-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'link_id',
            'project_id',
            'options',
            'link_status',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>